### ISSUE TITLE
Support for latest version of mongo

### ISSUE THREAD

**Issue by KevinHaisol** [jsreport/jsreport-mongodb-store#4]
Is this library still supported and work with the latest version of mongo?

**Comment by bjrmatos** [comment]
yes, the library is supported and should work with latest versions of mongo

do you have some problem? if so, try to paste the error message that you are getting and the exact version of mongo that you are using.

**Comment by KevinHaisol** [comment]
Thanks for the info, it's working, I"m new to jsreport so it was just a config error.
