### ISSUE TITLE
Rename collection name

### ISSUE THREAD

**Issue by DimaSavchenko** [jsreport/jsreport-mongodb-store#5]
Hi, guys! 
Do we have some solution to rename collection names?
eg: reportTemplates instead of templates
Thanks

**Comment by pofider** [comment]
Currently no, but I see it could be useful.
Would it be enough if we add option to add just collection name prefix?
Or do you need to fully customize the name for some (what?) reason?

**Comment by Kaffiend** [comment]
@pofider fully customized collection name would be preferred to fit to any name convention a database employs

**Comment by bjrmatos** [comment]
i've added support for adding a prefix to the collection name, fully customized names would require allowing to specify a map of standard names to new names in options, which requires the user to know all the collections that a particular jsreport installation has, and that does not sounds good.
